language: elixir
notifications:
  recipients:
    - teemu.harju@gmail.com
otp_release:
  - 17.0
before_install:
  - echo "yes" | sudo add-apt-repository ppa:travis-ci/memcached-sasl
  - sudo apt-get update
  - sudo apt-get install -y memcached
  - sudo service memcached start
